#pragma once
#ifndef  __MESSAGEDEFINE_H__
#define  __MESSAGEDEFINE_H__

#define WM_MESSAGE_NET_BASE					(WM_USER+0x1000)
/****************Net的消息定义开始****************************************************/
#define WM_MESSAGE_NET_ASYNCSOCK_BASE		(WM_MESSAGE_NET_BASE+0x0000)
#define WM_MESSAGE_NET_ASYNCSOCK_SEND		(WM_MESSAGE_NET_ASYNCSOCK_BASE + 1)	
#define WM_MESSAGE_NET_ASYNCSOCK_REPLY		(WM_MESSAGE_NET_ASYNCSOCK_BASE + 2)	
#define WM_MESSAGE_NET_ASYNCSOCK_VERIFY		(WM_MESSAGE_NET_ASYNCSOCK_BASE + 3)	
#define WM_MESSAGE_NET_ASYNCSOCK_NOTIFY		(WM_MESSAGE_NET_ASYNCSOCK_BASE + 4)	
// CThrdControl
#define WM_MESSAGE_NET_THREAD_BASE					(WM_MESSAGE_NET_BASE+0x0010)
#define WM_MESSAGE_NET_THREAD_CONNECT				(WM_MESSAGE_NET_THREAD_BASE + 1)
#define WM_MESSAGE_NET_THREAD_LIST					(WM_MESSAGE_NET_THREAD_BASE + 2)
#define WM_MESSAGE_NET_THREAD_DISCONNECT			(WM_MESSAGE_NET_THREAD_BASE + 3)
//ClientSocket
#define WM_MESSAGE_NET_CLIENT_BASE					(WM_MESSAGE_NET_BASE+0x0020)
#define WM_MESSAGE_NET_CLIENT_SENDDATA_PUMP 		(WM_MESSAGE_NET_CLIENT_BASE+1)
#define WM_MESSAGE_NET_CLIENT_THREAD_RETRYCONNECT 	(WM_MESSAGE_NET_CLIENT_BASE+2)
#define WM_MESSAGE_NET_CLIENT_TRANSFILE_PUMP		(WM_MESSAGE_NET_CLIENT_BASE+3)
#define WM_MESSAGE_NET_CLIENT_THRDTASK_PAUSE		(WM_MESSAGE_NET_CLIENT_BASE+4)
#define WM_MESSAGE_NET_CLIENT_THRDTASK_CONTINUE		(WM_MESSAGE_NET_CLIENT_BASE+5)
#define WM_MESSAGE_NET_CLIENT_THRDTASK_CANCEL 		(WM_MESSAGE_NET_CLIENT_BASE+6)
//ThrdServer.cpp
#define WM_MESSAGE_NET_SERVER_BASE					(WM_MESSAGE_NET_BASE+0x0030)
#define WM_MESSAGE_NET_SERVER_PUMP_SENDDATA 		(WM_MESSAGE_NET_SERVER_BASE+1)
#define WM_MESSAGE_NET_SERVER_THREAD_ATTACHSOCKET 	(WM_MESSAGE_NET_SERVER_BASE+2)

#endif